export const carActionsType = {
  GET_ALL_CARS: "GET_ALL_CARS",
  FETCH_SINGLE_CAR: "FETCH_SINGLE_CAR",
  RETURN_CAR: "RETURN_CAR",
  CLEAR_CAR: "CLEAR_CAR",
  DELETE_CAR: "DELETE_CAR",
  CLEAR_DELETE_CAR: "CLEAR_DELETE_CAR",
  UPDATE_CAR_DETAIL: "UPDATE_CAR_DETAIL",
};
